CREATE TABLE IF NOT EXISTS "sales-service".leads (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  run_id UUID REFERENCES "sales-service".runs(id) ON DELETE SET NULL,
  site_id TEXT,
  "business_name" TEXT,
  "website" TEXT,
  "address" TEXT,
  "city" TEXT,
  "province" TEXT,
  "zip" TEXT,
  "country" TEXT,
  "source" TEXT,
  "search_query" TEXT,
  "place_id" TEXT,
  "vicinity" TEXT,
  "latitude" TEXT,
  "longitude" TEXT,
  "formatted_phone_number" TEXT,
  "international_phone_number" TEXT,
  "rating" TEXT,
  "user_ratings_total" TEXT,
  "price_level" TEXT,
  "google_maps_url" TEXT,
  "business_status" TEXT,
  "opening_hours_available" TEXT,
  "photos_count" TEXT,
  "primary_type" TEXT,
  "editorial_summary" TEXT,
  "types" TEXT,
  "serves_beer" TEXT,
  "serves_breakfast" TEXT,
  "serves_brunch" TEXT,
  "serves_dinner" TEXT,
  "serves_lunch" TEXT,
  "serves_vegetarian_food" TEXT,
  "serves_wine" TEXT,
  UNIQUE (place_id)
);
CREATE INDEX IF NOT EXISTS leads_run_id_idx ON "sales-service".leads (run_id);
CREATE INDEX IF NOT EXISTS leads_site_id_idx ON "sales-service".leads (site_id);
