CREATE TABLE IF NOT EXISTS "sales-service".qualified_leads (
  id BIGSERIAL PRIMARY KEY,
  lead_id BIGINT REFERENCES "sales-service".leads(id) ON DELETE SET NULL,
  website TEXT,
  qualified_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  dedupe_key TEXT NOT NULL,
  fit_tier TEXT,
  review_status TEXT NOT NULL DEFAULT 'pending',
  run_id UUID REFERENCES "sales-service".runs(id) ON DELETE SET NULL,
  site_id TEXT,
  "province_normalized" TEXT,
  "city" TEXT,
  "province" TEXT,
  "prov" TEXT,
  "business_name" TEXT,
  "normalized_url" TEXT,
  "wordpress_detected" TEXT,
  "woocommerce_detected" TEXT,
  "wordpress_sort" TEXT,
  "woocommerce_sort" TEXT,
  "priority_score_sort" TEXT,
  "priority_score" TEXT,
  "priority_segment" TEXT,
  "final_url" TEXT,
  "reachable" TEXT,
  "http_status" TEXT,
  "platform" TEXT,
  "ecommerce" TEXT,
  "upload_present" TEXT,
  "upload_signals" TEXT,
  "email_found" TEXT,
  "fit_segment" TEXT,
  "fit_score" TEXT,
  "notes" TEXT,
  "address" TEXT,
  "zip" TEXT,
  "country" TEXT,
  "source" TEXT,
  "search_query" TEXT,
  "place_id" TEXT,
  "vicinity" TEXT,
  "latitude" TEXT,
  "longitude" TEXT,
  "formatted_phone_number" TEXT,
  "international_phone_number" TEXT,
  "rating" TEXT,
  "user_ratings_total" TEXT,
  "price_level" TEXT,
  "google_maps_url" TEXT,
  "business_status" TEXT,
  "opening_hours_available" TEXT,
  "photos_count" TEXT,
  "primary_type" TEXT,
  "editorial_summary" TEXT,
  "types" TEXT,
  "serves_beer" TEXT,
  "serves_breakfast" TEXT,
  "serves_brunch" TEXT,
  "serves_dinner" TEXT,
  "serves_lunch" TEXT,
  "serves_vegetarian_food" TEXT,
  "serves_wine" TEXT,
  UNIQUE (dedupe_key)
);
CREATE INDEX IF NOT EXISTS qualified_leads_run_id_idx ON "sales-service".qualified_leads (run_id);
CREATE INDEX IF NOT EXISTS qualified_leads_site_id_idx ON "sales-service".qualified_leads (site_id);
CREATE INDEX IF NOT EXISTS qualified_leads_review_status_idx ON "sales-service".qualified_leads (review_status);
