CREATE TABLE IF NOT EXISTS "sales-service".tracker_rows (
  id BIGSERIAL PRIMARY KEY,
  dedupe_key TEXT NOT NULL,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  run_id UUID REFERENCES "sales-service".runs(id) ON DELETE SET NULL,
  site_id TEXT,
  "sheet_blank" TEXT,
  "Company Name" TEXT,
  "Website" TEXT,
  "Contact Name" TEXT,
  "Contact Email" TEXT,
  "Contact Phone" TEXT,
  "Business Type" TEXT,
  "Has E-commerce?" TEXT,
  "Has Physical Store?" TEXT,
  "E-Commerce Platform" TEXT,
  "Offers Framing?" TEXT,
  "Offers Canvas?" TEXT,
  "Offers Acrylic?" TEXT,
  "Fit Tier" TEXT,
  "Notes" TEXT,
  "Address" TEXT,
  "City" TEXT,
  "State" TEXT,
  "Zip" TEXT,
  "Country" TEXT,
  "LinkedIn" TEXT,
  "Lead Source" TEXT,
  "Priority Score" TEXT,
  "Segment" TEXT,
  "Outreach Status" TEXT,
  "Last Contact Date" TEXT,
  "Next Step" TEXT,
  "Next Contact Date" TEXT,
  "Response Status" TEXT,
  "Demo Booked" TEXT,
  "Demo Date" TEXT,
  "Qualified" TEXT,
  "Proposal Amount" TEXT,
  "Interest Level" TEXT,
  "Close Date" TEXT,
  "Final Outcome" TEXT,
  "Website Platform" TEXT,
  "Assigned To" TEXT,
  "Assignment Date" TEXT,
  "Lead Owner Lock" TEXT,
  "Target Segment" TEXT,
  "Source" TEXT,
  UNIQUE (dedupe_key)
);
CREATE INDEX IF NOT EXISTS tracker_rows_site_id_idx ON "sales-service".tracker_rows (site_id);
